# Generated by Django 3.2.19 on 2023-06-15 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(db_index=True, max_length=64, verbose_name='Vin')),
                ('color', models.CharField(max_length=64, verbose_name='Color')),
                ('brand', models.IntegerField(choices=[(1, 'BMW'), (2, 'Mercedes'), (3, 'Lada'), (4, 'Lamborghini')], verbose_name='brand')),
                ('car_type', models.IntegerField(choices=[(1, 'sedan'), (2, 'hatchback'), (3, 'coupe'), (4, 'station wagon')], verbose_name='car_type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
